### PR TITLE
dpath out, crude iterating in

### PR DESCRIPTION
**Pull request by immanetize**
This adds an inelagant function in place of the dpath.util.search
invocation.

### CODE REVIEW

**Comment by pypingou** [comment]
May I ask why you want to remove it?

**Comment by sochotnicky** [comment]
I am pretty sure this is an attempted fix for https://bugzilla.redhat.com/show_bug.cgi?id=1187976 but it's...hacky and not really a solution.

**Comment by immanetize** [comment]
It's very hacky. I won't be offended at all if you deny the pull request, while snickering :)  I threw something in that seems to allow commit messages to trigger things in the short term, and will focus on the stuff being triggered while looking forward to something better.

**Comment by sochotnicky** [comment]
As mentioned elsewhere fixing the issue in dpath https://github.com/akesterson/dpath-python/issues/30 seems like the proper solution. After that I can update fedwatch to split config options into arrays before passing to dpath

**Comment by sochotnicky** [comment]
OK, given the underlying dpath  issue is fixed for quite a while - closing this one finally :-)

**Pull request closed without merging**
